---
- name: Install Docker, Docker Compose, and Make on Ubuntu 24.04
  hosts: monitoring_node
  become: true
  gather_facts: true

  vars:
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Add Docker's official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes

    - name: Install Docker Engine, containerd, and Docker Compose Plugin
      apt:
        name: "{{ docker_packages }}"
        state: present

    # This task allow running "docker compose" which is built-in & new , older is "docker-compose"
    # Since Makefile uses docker-compose, we perform this task too (ref : https://github.com/kamon-io/docker-grafana-graphite)
    - name: Install Docker Compose standalone (optional)
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'
      when: true

    # This task allows the user to run Docker commands without sudo
    - name: Add current user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Start and enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes