java_machine:
  hosts:
    java_machine_1:
      ansible_host: 172.31.15.208
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/aws_ad89.pem


monitoring_machine:
  hosts:
    machine_machine_1:
      ansible_host: 172.31.15.208
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/aws_ad89.pem