THREADS=8
DURATION_MINUTES=5
TIMES=$((1000 * 1000 * 1000))
NUMBER=$((1000 * 1000))
METRIC_PREFIX="work-71"
PRINT_PERCENT=10

# Threads, Duration, Times, Number
./send_curl.sh "cores-2" "3020" "$METRIC_PREFIX" \
    $THREADS $DURATION_MINUTES $TIMES $NUMBER $PRINT_PERCENT

echo

./send_curl.sh "cores-4" "3020" "$METRIC_PREFIX" \
    $THREADS $DURATION_MINUTES $TIMES $NUMBER $PRINT_PERCENT

echo

./send_curl.sh "cores-8" "3020" "$METRIC_PREFIX" \
    $THREADS $DURATION_MINUTES $TIMES $NUMBER $PRINT_PERCENT

# for local testing
# ./send_curl.sh "localhost" "3020" "$METRIC_PREFIX" \
#     $THREADS $DURATION_MINUTES $TIMES $NUMBER $PRINT_PERCENT

echo
